version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: >
      bash -c "
        docker-entrypoint.sh mysqld &
        sleep 30 && 
        mysql -u root -p123456 -e 'CREATE DATABASE IF NOT EXISTS store;' && 
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo

  ui:
    image: kensc/lenguajes2024ui:0.0.1
    container_name: ui
    hostname: ui
    environment:
      - NEXT_PUBLIC_API=http://localhost:8080   
    ports:
      - "3000:3000"
    networks:
      - demo

  api:
    image: kensc/lenguajes2024api:0.0.1
    container_name: api
    hostname: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB=Server=mysql;Database=store;Uid=root;Pwd=123456;
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - demo

networks:
  demo:
    driver: bridge