version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
#    networks:
#      internal_net:
#        ipv4_address: 192.168.1.10
    command: >
      bash -c "
        docker-entrypoint.sh mysqld &
        sleep 30 && 
        mysql -u root -p123456 -e 'CREATE DATABASE IF NOT EXISTS MyStoreApi;' && 
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo

  ui:
    image: alvaro944/app:latest
    container_name: ui
    hostname: ui
    environment:
      #- API=192.168.1.12:57600
      - NODE_ENV=http://localhost:8080      
    ports:
      - "3000:3000"
    networks:
      - demo

  api:
    image: alvaro944/api:latest
    container_name: api
    hostname: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- mysql=192.168.1.10:3306
      - DB=Server=mysql;Database=MyStoreApi;Uid=root;Pwd=123456
      - JWT_GLOBAL="192.168.18.8:7161"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - demo

networks:
  demo:
    driver: bridge
