apiVersion: v1
kind: Pod
metadata:
  labels:
    app: csharpapi-pod
  name: csharpapi-pod
spec:
  containers:
  - image: docker.io/ucr/csharp-api-rest:latest
    name: csharpapi
    ports:
    - containerPort: 8080
      hostPort: 8081
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: springapi-pod
  name: springapi-pod
spec:
  containers:
  - args:
    - mvn
    - org.springframework.boot:spring-boot-maven-plugin:run
    image: docker.io/ucr/java-api-rest:latest
    name: springapi
    ports:
    - containerPort: 8080
      hostPort: 8080
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: reactapp-pod
  name: reactapp-pod
spec:
  containers:
  - args:
    - npm
    - run
    - dev
    image: docker.io/ucr/react/my-app:latest
    name: reactapp
    ports:
    - containerPort: 3000
      hostPort: 8082
  restartPolicy: Never


