apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharpapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharpapi-pod
  template:
    metadata:
      labels:
        app: csharpapi-pod
    spec:
      containers:
      - image: docker.io/ucr/csharp-api-rest:latest
        name: csharpapi
        ports:
        - containerPort: 8080
          hostPort: 8080
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapi-pod
  template:
    metadata:
      labels:
        app: springapi-pod
    spec:
      containers:
      - args:
        - mvn
        - org.springframework.boot:spring-boot-maven-plugin:run
        image: docker.io/ucr/java-api-rest:latest
        name: springapi
        ports:
        - containerPort: 8080
          hostPort: 8081
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp-pod
  template:
    metadata:
      labels:
        app: reactapp-pod
    spec:
      containers:
      - args:
        - npm
        - run
        - dev
        image: docker.io/ucr/react/my-app:latest
        name: reactapp
        ports:
        - containerPort: 3000
          hostPort: 8082
      restartPolicy: Always