# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C02231

on:
  push:
    branches: [ "DevOps_C02231" ]
  pull_request:
    branches: [ "DevOps_C02231" ]

jobs:
  unitTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C02231/Store/Lab7
        dotnet restore
    - name: Build
      run: |
        cd C02231/Store/Lab7
        dotnet build --no-restore
    - name: Test
      run: |
        cd C02231/Store/Lab7
        dotnet test --no-build --verbosity normal
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd  C02231/Store/Lab7
        docker image build -t lani06/storeapi:latest .
        docker image build -t lani06/storeapi:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC02231  }}" | docker login -u "pchavesr29@gmail.com" --password-stdin
        docker push lani06/storeapi:latest
        docker push lani06/storeapi:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd  C02231\Store\React\nextjs-dashboard
        docker image build -t lani06/react:latest .
        docker image build -t lani06/react:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC02231  }}" | docker login -u "pchavesr29@gmail.com" --password-stdin
        docker push lani06/react:latest
        docker push lani06/react:0.0.1    