# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C18780

on:
  push:
    branches: [ "DevOps_C18780" ]
  pull_request:
    branches: [ "DevOps_C18780" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: sys
          MYSQL_USER: user
          MYSQL_PASSWORD: 123456

    steps:
    - uses: actions/checkout@v4

    - name: Wait for MySQL to be healthy
      run: |
        docker ps -a
        #docker-compose run --rm wait-for-it.sh mysql:3306 -t 30

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C18780/backend
        dotnet restore
    - name: Build
      run: |
        cd C18780/backend
        dotnet build --no-restore
    - name: Test
      run: |
        cd C18780/backend
        dotnet test --no-build --verbosity normal
        
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C18780/backend
        docker image build -t zjean42/api:latest .
        docker image build -t zjean42/api:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC18780  }}" | docker login -u "zjeancarlo42@gmail.com" --password-stdin
        docker push zjean42/api:latest
        docker push zjean42/api:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C18780\primer trabajo\demo6\nextjs-dashboard
        docker image build -t zjean42/ui:latest .
        docker image build -t zjean42/ui:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC18780  }}" | docker login -u "zjeancarlo42@gmail.com" --password-stdin
        docker push zjean42/ui:latest
        docker push zjean42/ui:0.0.1   
