# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C27507

on:
  push:
    branches: [ "C27507" ]
  pull_request:
    branches: [ "C27507" ]

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MySQL to be healthy
      run: |
        docker run -d --name mysql_db -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=MyStoreApi mysql:latest
        docker ps -a
        docker exec mysql_db mysql -u root -p123456 -e "CREATE DATABASE IF NOT EXISTS MyStoreApi;"
        
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C27507/C27507_Lab7
        dotnet restore
    - name: Build
      run: |
        cd C27507/C27507_Lab7
        dotnet build --no-restore    
    - name: Test
      run: |
        cd C27507/C27507_Lab7
        dotnet test --no-build --verbosity normal
        
  publish-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27507/C27507_Lab7
        docker image build -t alvaro944/store_api_leng_2024:latest .
        echo "${{ secrets.DOCKERHUBPASS_C27507 }}" | docker login -u "alvaro.siles@ucr.ac.cr" --password-stdin
        docker push alvaro944/store_api_leng_2024:latest
        
  publish-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd C27507/C27507_Lab1/nodeJS_Lab3/nextjs-dashboard
        docker image build -t alvaro944/store_api_leng_2024:latest .        
        echo "${{ secrets.DOCKERHUBPASS_C27507 }}" | docker login -u "alvaro.siles@ucr.ac.cr" --password-stdin
        docker push alvaro944/store_api_leng_2024:latest
      
                
        
